import type { Workout } from '../models';

export const WORKOUTS_TEMPLATES: Array<Workout> = [
  {
    userId: 'user-1',
    workoutId: 5,
    name: '5er Split',
    lastUpdated: 815350254,
    units: [
      {
        name: '#1 Brust Trizeps',
        exercises: [
          {
            name: 'Bankdrücken',
            muscleGroupPrimary: 'chest',
            muscleGroupSecondary: 'triceps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Fliegende Kurzhantel',
            muscleGroupPrimary: 'chest',
            muscleGroupSecondary: 'shoulders',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Trizepsdrücken stehend Kurzhantel',
            muscleGroupPrimary: 'triceps',
            muscleGroupSecondary: null,
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
        ],
      },
      {
        name: '#2 Schulter Bizeps',
        exercises: [
          {
            name: 'Schulterdrücken Kurzhantel',
            muscleGroupPrimary: 'shoulders',
            muscleGroupSecondary: 'triceps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Seitheben Kurzhantel',
            muscleGroupPrimary: 'shoulders',
            muscleGroupSecondary: 'triceps',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Hammercurls Kurzhantel',
            muscleGroupPrimary: 'biceps',
            muscleGroupSecondary: 'forearms',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
        ],
      },
      {
        name: '#3 Beine Waden',
        exercises: [
          {
            name: 'Kniebeugen Kurzhantel',
            muscleGroupPrimary: 'quads',
            muscleGroupSecondary: 'abductors',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Ausfallschritte Kurzhantel',
            muscleGroupPrimary: 'quads',
            muscleGroupSecondary: 'adductors',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Kreuzheben gestreckt Kurzhantel',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: 'hamstrings',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Wadenheben einzeln Kurzhantel',
            muscleGroupPrimary: 'calves',
            muscleGroupSecondary: null,
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
        ],
      },
      {
        name: '#4 Rücken Nacken',
        exercises: [
          {
            name: 'Rudern einzeln Kurzhantel',
            muscleGroupPrimary: 'lats',
            muscleGroupSecondary: 'traps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Seitwärtsheben vorgebeugt Kurzhantel (Butterfly Reverse)',
            muscleGroupPrimary: 'traps',
            muscleGroupSecondary: 'shoulders',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Nackenheben Kurzhantel',
            muscleGroupPrimary: 'neck',
            muscleGroupSecondary: 'traps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
        ],
      },
      {
        name: '#5 Bauch Rumpf',
        exercises: [
          {
            name: 'Unterarmstütz',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: 'abs',
            sets: '2-3',
            reps: '60s',
            rest: null,
          },
          {
            name: 'Seitstütz',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: 'abs',
            sets: '1-2',
            reps: '30s',
            rest: null,
          },
          {
            name: 'Crunches',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: null,
            sets: '2-3',
            reps: 'max',
            rest: null,
          },
          {
            name: 'Russian Twist',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: 'abs',
            sets: '1-2',
            reps: 'max',
            rest: null,
          },
        ],
      },
    ],
  },
  {
    userId: 'user-1',
    workoutId: 4,
    name: '4er Split',
    lastUpdated: 1756804801,
    units: [
      {
        name: '#1 Brust Nacken',
        exercises: [
          {
            name: 'Bankdrücken',
            muscleGroupPrimary: 'chest',
            muscleGroupSecondary: 'triceps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Fliegende Kurzhantel',
            muscleGroupPrimary: 'chest',
            muscleGroupSecondary: 'shoulders',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Nackenheben Kurzhantel',
            muscleGroupPrimary: 'neck',
            muscleGroupSecondary: 'traps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
        ],
      },
      {
        name: '#2 Rücken Rumpf Bauch',
        exercises: [
          {
            name: 'Rudern einzeln Kurzhantel',
            muscleGroupPrimary: 'lats',
            muscleGroupSecondary: 'traps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Seitwärtsheben vorgebeugt Kurzhantel (Butterfly Reverse)',
            muscleGroupPrimary: 'traps',
            muscleGroupSecondary: 'shoulders',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Unterarmstütz',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: 'abs',
            sets: '2-3',
            reps: '60s',
            rest: null,
          },
          {
            name: 'Seitstütz',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: 'abs',
            sets: '1-2',
            reps: '30s',
            rest: null,
          },
          {
            name: 'Crunches',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: null,
            sets: '2-3',
            reps: 'max',
            rest: null,
          },
          {
            name: 'Russian Twist',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: 'abs',
            sets: '1-2',
            reps: 'max',
            rest: null,
          },
        ],
      },
      {
        name: '#3 Schultern Arme',
        exercises: [
          {
            name: 'Schulterdrücken Kurzhantel',
            muscleGroupPrimary: 'shoulders',
            muscleGroupSecondary: 'triceps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Seitheben Kurzhantel',
            muscleGroupPrimary: 'shoulders',
            muscleGroupSecondary: 'triceps',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Hammercurls Kurzhantel',
            muscleGroupPrimary: 'biceps',
            muscleGroupSecondary: 'forearms',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Trizepsdrücken stehend Kurzhantel',
            muscleGroupPrimary: 'triceps',
            muscleGroupSecondary: null,
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
        ],
      },
      {
        name: '#4 Beine Waden',
        exercises: [
          {
            name: 'Kniebeugen Kurzhantel',
            muscleGroupPrimary: 'quads',
            muscleGroupSecondary: 'abductors',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Ausfallschritte Kurzhantel',
            muscleGroupPrimary: 'quads',
            muscleGroupSecondary: 'adductors',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Kreuzheben gestreckt Kurzhantel',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: 'hamstrings',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Wadenheben einzeln Kurzhantel',
            muscleGroupPrimary: 'calves',
            muscleGroupSecondary: null,
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
        ],
      },
    ],
  },
  {
    userId: 'user-1',
    workoutId: 2,
    name: '2er Split',
    lastUpdated: 1756804801,
    units: [
      {
        name: '#1 Rücken Beine Brust',
        exercises: [
          {
            name: 'Rudern einzeln Kurzhantel',
            muscleGroupPrimary: 'lats',
            muscleGroupSecondary: 'traps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Seitwärtsheben vorgebeugt Kurzhantel (Butterfly Reverse)',
            muscleGroupPrimary: 'traps',
            muscleGroupSecondary: 'shoulders',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Kniebeugen Kurzhantel',
            muscleGroupPrimary: 'quads',
            muscleGroupSecondary: 'abductors',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Ausfallschritte Kurzhantel',
            muscleGroupPrimary: 'quads',
            muscleGroupSecondary: 'adductors',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Kreuzheben gestreckt Kurzhantel',
            muscleGroupPrimary: 'core',
            muscleGroupSecondary: 'hamstrings',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Bankdrücken',
            muscleGroupPrimary: 'chest',
            muscleGroupSecondary: 'triceps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
        ],
      },
      {
        name: '#2 Schultern Nacken Arme',
        exercises: [
          {
            name: 'Schulterdrücken Kurzhantel',
            muscleGroupPrimary: 'shoulders',
            muscleGroupSecondary: 'triceps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Seitheben Kurzhantel',
            muscleGroupPrimary: 'shoulders',
            muscleGroupSecondary: 'triceps',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Nackenheben Kurzhantel',
            muscleGroupPrimary: 'neck',
            muscleGroupSecondary: 'traps',
            sets: '2-3',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Trizepsdrücken stehend Kurzhantel',
            muscleGroupPrimary: 'triceps',
            muscleGroupSecondary: null,
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
          {
            name: 'Hammercurls Kurzhantel',
            muscleGroupPrimary: 'biceps',
            muscleGroupSecondary: 'forearms',
            sets: '1-2',
            reps: '15-18',
            rest: null,
          },
        ],
      },
    ],
  },
];
